Write-Host '========================================'
Write-Host 'iFlyGo Windows 容器'
Write-Host 'GitHub: https://github.com/iflyelf/iflygo'
Write-Host '========================================'
Write-Host ''
Write-Host '二进制文件位置:'
Write-Host '  iflygo.exe       -> C:\iflygo\bin\iflygo.exe'
Write-Host '  iflygo-cert.exe  -> C:\iflygo\bin\iflygo-cert.exe'
Write-Host ''
Write-Host '配置模板位置:'
Write-Host '  Server 模板 -> C:\iflygo\config\server-config-template.yml'
Write-Host '  Client 模板 -> C:\iflygo\config\client-config-template.yml'
Write-Host ''
Write-Host '提取到 Windows 宿主机:'
Write-Host '  docker cp <容器ID>:C:\iflygo\bin\iflygo.exe C:\iflygo\'
Write-Host '  docker cp <容器ID>:C:\iflygo\bin\iflygo-cert.exe C:\iflygo\'
Write-Host ''
Write-Host '或直接下载 GitHub Release:'
Write-Host '  https://github.com/iflyelf/iflygo/releases/latest'
Write-Host ''
Write-Host '查看版本信息:'
C:\iflygo\bin\iflygo.exe -version
Write-Host ''
Write-Host '========================================'
Write-Host '容器保持运行中... 按 Ctrl+C 停止'
Write-Host '========================================'
Start-Sleep -Seconds 2147483
